# Activate 3

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: r0781669/laravel
        command: ["/bin/bash"]
        args:
          - "-c"
          - |
            cd /var/www/html/
            composer install --no-scripts --no-autoloader
            composer dump-autoload --optimize
            chmod 755 public/
            apache2-foreground
        # command: ["/bin/bash", "-c", "apt-get clean && apt-get update && docker-php-ext-install mysqli && apache2ctl -DFOREGROUND"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: apache-volume
          mountPath: /var/www/html/
        - name: apache-volume-conf
          mountPath: /etc/apache2/sites-enabled/
      volumes:
      - name: apache-volume
        persistentVolumeClaim:
          claimName: apache-pvc
      - name: apache-volume-conf
        persistentVolumeClaim:
          claimName: apache-pvc-conf