apiVersion: v1
kind: PersistentVolume
metadata:
  name: ansible-test-project-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.26.192.186
    path: /nfs/shareddir/ansible-test-project/db
