---

- name: Copy file to remote host
  template:
    src: ../templates/record.yaml.j2
    dest: "/etc/bind/{{ item }}"
    owner: root
    group: bind
    mode: 0644
    force: yes
  with_items: "{{ url_list }}"



- name: Check if zone exists in named.conf.local
  shell: grep -q "{{ item }}" /etc/bind/named.conf.local
  changed_when: false
  register: zone_check
  with_items: "{{ url_list }}"
  ignore_errors: true

- name: Add zone to named.conf.local
  lineinfile:
    path: /etc/bind/named.conf.local
    regexp: '^zone "{{ item }}"'
    line: |
      zone "{{ item }}" {
        notify no;
        allow-update {none;};
        type master;
        file "/etc/bind/{{ item }}";
      };
  with_items: "{{ url_list }}"
  when: zone_check.results | rejectattr('rc', 'eq', 0) | selectattr('item', 'equalto', item) | list | length > 0
  register: zone_added


- name: Restarting BIND service
  service:
    name: bind9
    daemon_reload: yes
    state: restarted
    enabled: True
  when: zone_added.changed
  

- name: Flush DNS caches
  shell:
    cmd: resolvectl flush-caches
  when: zone_added.changed

...