---

- name: Copy file to remote host
  template:
    src: ../templates/record.yaml.j2
    dest: "/etc/bind/{{ item }}"
    owner: root
    group: bind
    mode: 644
    force: yes
  with_items: "{{ url_list }}"


- name: Add zone to named.conf.local
  lineinfile:
    path: /etc/bind/named.conf.local
    regexp: '^zone "{{ item }}"'
    line: |
      zone "{{ item }}" {
        notify no;
        allow-update {none;};
        type master;
        file "/etc/bind/{{ item }}";
      };
  with_items: "{{ url_list }}"





# - name: Delete files on remote host
#   file:
#     path: "/etc/bind/{{ item }}"
#     state: absent
#   with_items: "{{ url_list }}"



# - name: Remove zone from named.conf.local
#   replace:
#     path: /etc/bind/named.conf.local
#     regexp: '^zone "example.com" {\s*notify no;\n\s*allow-update {none;};\n\s*type master;\n\s*file "/etc/bind/example.com";\n\s*};\n?'
#     replace: ""











# - name: Restarting BIND service
#   service:
#     name: named
#     daemon_reload: yes
#     state: restarted
#     enabled: True

...