---

- name: Create new user
  user:
    name: "{{ new_username }}"
    createhome: yes
    shell: /bin/bash
    password: "{{ new_user_password | password_hash('sha512', 'mysecretsalt') }}"

- name: Add SSH public key for new user
  authorized_key:
    user: "{{ new_username }}"
    state: present
    key: "{{ new_user_public_key }}"

- name: Add new user to sudo group
  user:
    name: "{{ new_username }}"
    groups: sudo
    append: yes
...