---

- hosts: localhost_setup
  gather_facts: no
  connection: local
  become: true
  roles:
    - Delete-all-resources-by-namespace

- hosts: dns_server
  gather_facts: no
  become: true
  roles:
    - Delete-dns-record


...