---

# This doesn't work and then i mean the second task because of "common_name" to "organizational_unit_name"

# - name: Generate private key
#   openssl_privatekey:
#     path: /home/wael/openssl/root.key
#     # cipher: aes256
#     # passphrase: ""

# - name: Generate self-signed certificate
#   openssl_certificate:
#     path: /home/wael/openssl/root.crt
#     privatekey_path: /home/wael/openssl/root.key
#     privatekey_passphrase: ""
#     provider: selfsigned
#     # common_name: "My Root CA - Team CCS03"
#     # country_name: BE
#     # state_or_province_name: Antwerpen
#     # locality_name: Geel
#     # organization_name: Team ccs03
#     # organizational_unit_name: De slimste studenten
#     selfsigned_not_after: "+36500d"




- name: Generate private key
  shell:
    cmd: openssl genpkey -algorithm RSA -out /home/wael/openssl/root.key


- name: Generate self-signed certificate
  shell:
    cmd: openssl req -new -x509 -key /home/wael/openssl/root.key -out /home/wael/openssl/root.crt -days 3650 -subj "/C=BE/ST=Antwerpen/L=Geel/O=Team CCS03/OU=De slimste studenten/CN=My Root CA - Team CCS03"


### Certificaat in je browser steken. (firefox)
# Add the root certificate to your browser: 
# You can now add the root.crt file to your browser's certificate store. 
# This process varies depending on the browser you are using. In Firefox, 
# you can import the certificate by going to Preferences -> Privacy & Security 
# -> Certificates -> View Certificates -> Authorities -> Import.

# Je moet btw owner zijn van die file anders kan je hem er niet insteken!!!

...