---

- name: SEE if the namespace actually exists
  shell:
    cmd: ./rancher kubectl get namespaces --token={{ bearer_token }} | awk '/{{ new_namespace }}/{print $1}'
    chdir: "{{ path_to_rancher_file }}"
  register: namespace_exists

# - name: Debug namespace Test
#   debug:
#     msg: "test"
#   when: namespace_exists.stdout_lines | length == 0


- block:
    - name: Scan "files" directory for YAML files
      find:
        paths: "{{ backup_ansible_playbook }}/roles/{{ new_namespace }}/files/"
        patterns: "*.yaml"
      register: yaml_files

    # - name: Debug YAML files
    #   debug:
    #     msg: "{{ item.path }}" 
    #   loop: "{{ yaml_files.files | sort(attribute='path') }}"

    - name: Create a new namespace
      shell:
        cmd: ./rancher kubectl create namespace {{ new_namespace }}
        chdir: "{{ path_to_rancher_file }}"

    - name: Create a BASE folder in the NFS directory
      file:
        path: "{{ nfs_file_path }}{{ new_namespace }}"
        state: directory
        mode: '775'
    
    - name: Create a folder for the database volume
      file:
        path: "{{ nfs_file_path }}{{ new_namespace }}/{{ item }}"
        state: directory
        mode: '775'
      with_items:
        - db
        - website

    - name: Executing every Yaml file with kubctl apply
      shell:
        cmd: ./rancher kubectl apply -f "{{ item.path }}" -n {{ new_namespace }} --token={{ bearer_token }}
        chdir: "{{ path_to_rancher_file }}"
      loop: "{{ yaml_files.files | sort(attribute='path') }}"

    # Start - Put default HTML page on the website
    - name: Check if index.html exists
      stat:
        path: "{{ nfs_file_path ~ new_namespace }}/website/index.html"
      register: index_html_exists

    - name: Get IP address of the machine
      shell: hostname -I | awk '{print $1}'
      register: machine_ip
      when: not index_html_exists.stat.exists

    - name: Put default index.html page
      copy:
        content: |
          <html>
            <head>
              <title>Welcome to your Website</title>
            </head>
            <body>
              <h1>Welcome to your project: {{ new_namespace }}</h1>
              <p>You can get here with FTP</p>
              <p>Instructions go to ip-addres: {{ machine_ip.stdout }}</p>

            </body>
          </html>
        dest: "{{ nfs_file_path ~ new_namespace }}/website/index.html"
      when: not index_html_exists.stat.exists
    # End - Put default HTML page on the website
  when: namespace_exists.stdout_lines | length == 0
  
...