---

# - hosts: localhost
#   gather_facts: no
#   connection: local
#   become: true
#   roles:
#     # - Basic-information-about-system
#     # - Basic-info-pod-name-ipadress

#     - Create-project-example
#     # - Delete-all-resources-by-namespace
#     # - Create-root-certificate

- hosts: dns_server
  gather_facts: no
  become: true
  roles:
    - Create-dns-record

...