---

# - name: Updaten van de repository
#   apt:
#     update_cache: 'yes'
#     cache_valid_time: 3600
#     upgrade: 'yes'


- name: Install duplicity
  apt:
    name: duplicity
    state: present


...