apiVersion: v1
kind: PersistentVolume
metadata:
  name: ansible-test-project-website-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.26.192.186
    path: /nfs/shareddir/ansible-test-project/website
    