apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-test-project-website-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: ansible-test-project-website-pv
