apiVersion: v1
kind: PersistentVolume
metadata:
  name: ansible-test-project-website-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.26.103.3
    path: /nfs/shareddir/wael/ansible-test-project/website

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ansible-test-project-website-pv-virtualhost
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.26.103.3
    path: /nfs/shareddir/wael/ansible-test-project/website_virtualhost