apiVersion: v1
kind: PersistentVolume
metadata:
  name: waeltestez-website-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.26.103.3
    path: /nfs/shareddir/waeltestidk/waeltestez/website

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: waeltestez-website-pv-virtualhost
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.26.103.3
    path: /nfs/shareddir/waeltestidk/waeltestez/website_virtualhost