apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waeltestez-website-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: waeltestez-website-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waeltestez-website-pvc-virtualhost
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: waeltestez-website-pv-virtualhost