---

- name: Create a new namespace
  shell:
    cmd: kubectl create namespace {{ new_namespace }} --kubeconfig "{{ path_to_rancher_config_file }}"

- name: Create a Username folder in the NFS directory
  file:
    path: "{{ nfs_file_path }}{{ username }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create a project folder in the NFS directory
  file:
    path: "{{ nfs_file_path }}{{ username }}/{{ new_namespace }}"
    state: directory
    mode: '775'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create a directory called "files" for the yaml files
  file:
    path: "{{ current_playbook }}/files"
    state: directory
    mode: '755'

- name: Create a directory called "certificates" for the yaml files
  file:
    path: "{{ current_playbook }}/certificates"
    state: directory
    mode: '755'


# Start Database
- name: Create a folder for the database volume
  file:
    path: "{{ nfs_file_path }}{{ username }}/{{ new_namespace }}/db"
    state: directory
    mode: '775'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Encode the root password
  shell:
    cmd: echo -n "{{ database_root_password }}" | base64
  register: database_root_password_encrypted


- name: Jinja2 to yaml file - Database Deploy ALL
  template:
    src: "../templates/{{ item.src }}"
    dest: "{{ current_playbook }}/files/{{ item.dest }}"
  with_items: "{{ database_k8s_files }}"


- name: Create "Database" Deploy ALL
  shell:
    cmd: kubectl apply -f "{{ current_playbook }}/files/{{ item.dest }}" -n {{ new_namespace }} --token={{ bearer_token }} --kubeconfig "{{ path_to_rancher_config_file }}"
  with_items: "{{ database_k8s_files }}"
# End database



# Start phpmyadmin
- name: Generate private key
  openssl_privatekey:
    path: "{{ current_playbook }}/certificates/{{ phpmyadmin_certificate_name }}.key"
    size: 2048
    mode: 0644

- name: Generate certificate signing request
  openssl_csr:
    path: "{{ current_playbook }}/certificates/{{ phpmyadmin_certificate_name }}.csr"
    privatekey_path: "{{ current_playbook }}/certificates/{{ phpmyadmin_certificate_name }}.key"
    common_name: "{{ phpmyadmin_ingress_url }}"

- name: Generate certificate
  openssl_certificate:
    path: "{{ current_playbook }}/certificates/{{ phpmyadmin_certificate_name }}.crt"
    csr_path: "{{ current_playbook }}/certificates/{{ phpmyadmin_certificate_name }}.csr"
    provider: selfsigned
    privatekey_path: "{{ current_playbook }}/certificates/{{ phpmyadmin_certificate_name }}.key"

- name: Sign certificate with root certificate
  openssl_certificate:
    path: "{{ current_playbook }}/certificates/{{ phpmyadmin_certificate_name }}.crt"
    csr_path: "{{ current_playbook }}/certificates/{{ phpmyadmin_certificate_name }}.csr"
    provider: ownca
    ownca_path: "{{ root_certificate_directory }}/root.crt"
    ownca_privatekey_path: "{{ root_certificate_directory }}/root.key"
    # ownca_privatekey_passphrase: mypassphrase

- name: Encrypt tls.crt and read it
  shell:
    cmd: cat "{{ current_playbook }}/certificates/{{ phpmyadmin_certificate_name }}.crt" | base64 | tr -d '\n'
  register: phpmyadmin_secret_crt

- name: Encrypt tls.key and read it
  shell:
    cmd: cat "{{ current_playbook }}/certificates/{{ phpmyadmin_certificate_name }}.key" | base64 | tr -d '\n'
  register: phpmyadmin_secret_key

- name: Jinja2 to yaml file - PHPmyAdmin Deploy ALL
  template:
    src: "../templates/{{ item.src }}"
    dest: "{{ current_playbook }}/files/{{ item.dest }}"
  with_items: "{{ phpmyadmin_k8s_files }}"


- name: Create "PHPmyAdmin" Deploy ALL
  shell:
    cmd: kubectl apply -f "{{ current_playbook }}/files/{{ item.dest }}" -n {{ new_namespace }} --token={{ bearer_token }} --kubeconfig "{{ path_to_rancher_config_file }}"
  with_items: "{{ phpmyadmin_k8s_files }}"
# End phpmyadmin




# Start website
- name: Create a folder for the website volume
  file:
    path: "{{ nfs_file_path }}{{ username }}/{{ new_namespace }}/website"
    state: directory
    mode: '775'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create a folder for the Website_virtualhost volume
  file:
    path: "{{ nfs_file_path }}{{ username }}/{{ new_namespace }}/website_virtualhost"
    state: directory
    mode: '775'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Jinja2 to config file - Website_virtualhost file
  template:
    src: "../templates/website-virtualhost.j2"
    dest: "{{ item }}"
  with_items:
    - "{{ nfs_file_path }}{{ username }}/{{ new_namespace }}/website_virtualhost/apache.conf"
    - "{{ current_playbook }}/files/apache.conf"



- name: Generate private key
  openssl_privatekey:
    path: "{{ current_playbook }}/certificates/{{ website_certificate_name }}.key"
    size: 2048
    mode: 0644

- name: Generate certificate signing request
  openssl_csr:
    path: "{{ current_playbook }}/certificates/{{ website_certificate_name }}.csr"
    privatekey_path: "{{ current_playbook }}/certificates/{{ website_certificate_name }}.key"
    common_name: "{{ website_ingress_url }}"

- name: Generate certificate
  openssl_certificate:
    path: "{{ current_playbook }}/certificates/{{ website_certificate_name }}.crt"
    csr_path: "{{ current_playbook }}/certificates/{{ website_certificate_name }}.csr"
    provider: selfsigned
    privatekey_path: "{{ current_playbook }}/certificates/{{ website_certificate_name }}.key"

- name: Sign certificate with root certificate
  openssl_certificate:
    path: "{{ current_playbook }}/certificates/{{ website_certificate_name }}.crt"
    csr_path: "{{ current_playbook }}/certificates/{{ website_certificate_name }}.csr"
    provider: ownca
    ownca_path: "{{ root_certificate_directory }}/root.crt"
    ownca_privatekey_path: "{{ root_certificate_directory }}/root.key"
    # ownca_privatekey_passphrase: mypassphrase

- name: Encrypt tls.crt and read it
  shell:
    cmd: cat "{{ current_playbook }}/certificates/{{ website_certificate_name }}.crt" | base64 | tr -d '\n'
  register: website_secret_crt

- name: Encrypt tls.key and read it
  shell:
    cmd: cat "{{ current_playbook }}/certificates/{{ website_certificate_name }}.key" | base64 | tr -d '\n'
  register: website_secret_key

- name: Jinja2 to yaml file - Website Deploy ALL
  template:
    src: "../templates/{{ item.src }}"
    dest: "{{ current_playbook }}/files/{{ item.dest }}"
  with_items: "{{ website_k8s_files }}"


- name: Create "Website" Deploy ALL
  shell:
    cmd: kubectl apply -f "{{ current_playbook }}/files/{{ item.dest }}" -n {{ new_namespace }} --token={{ bearer_token }} --kubeconfig "{{ path_to_rancher_config_file }}"
  with_items: "{{ website_k8s_files }}"
# End website




# Start - Put default HTML page on the website
- name: Check if anything exists in website directory
  command: ls -A "{{ nfs_file_path }}{{ username }}/{{ new_namespace }}/website"
  register: website_files


- name: Get IP address of the machine
  shell: hostname -I | awk '{print $1}'
  register: machine_ip
  when: not website_files.stdout_lines | length > 0

- name: Create a public folder in the website directory
  file:
    path: "{{ nfs_file_path }}{{ username }}/{{ new_namespace }}/website/public"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  when: not website_files.stdout_lines | length > 0

- name: Put default index.html page
  copy:
    content: |
      <html>
        <head>
          <title>Welcome to your Website</title>
        </head>
        <body>
          <h1>Welcome to your project: {{ new_namespace }}</h1>
          <p>You can get here with FTP</p>
          <p>Instructions go to ip-addres: {{ machine_ip.stdout }}</p>

        </body>
      </html>
    dest: "{{ nfs_file_path }}{{ username }}/{{ new_namespace }}/website/public/index.html"
    owner: "{{ username }}"
    group: "{{ username }}"
  when: not website_files.stdout_lines | length > 0
# End - Put default HTML page on the website




# Start - Backup the Yaml file
- name: Create a directory in the roles directory
  file:
    path: "{{ backup_ansible_playbook }}/roles/{{ new_namespace }}"
    state: directory
    mode: '755'

- name: Create directories for new role
  file:
    path: "{{ backup_ansible_playbook }}/roles/{{ new_namespace }}/{{ item }}"
    state: directory
    mode: '755'
  with_items:
    - defaults
    - files
    - tasks
    - certificates

- name: Copy files to backup directory
  copy:
    src: "{{ item.src }}"
    dest: "{{ backup_ansible_playbook }}/roles/{{ new_namespace }}/{{ item.dest }}"
  with_items:
    - { src: "../files/", dest: "files/" }
    - { src: "../certificates/", dest: "certificates/" }



- name: Create a main.yaml file for defaults
  copy:
    content: |
      ---

      username: {{ username }}
      new_namespace: {{ new_namespace }}

      ...
    dest: "{{ backup_ansible_playbook }}/roles/{{ new_namespace }}/defaults/main.yaml"

- name: Create a main.yaml file for tasks
  copy:
    src: ../templates/main.yml
    dest: "{{ backup_ansible_playbook }}/roles/{{ new_namespace }}/tasks/main.yaml"
# End - Backup the Yaml file



# Start - Cleaning up
- name: Cleaning up playbook
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ current_playbook }}/files"
    - "{{ current_playbook }}/certificates"
# End - Cleaning up

...