apiVersion: v1
kind: PersistentVolume
metadata:
  name: waeltest-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.26.103.3
    path: /nfs/shareddir/waeltestidk/waeltest/db
