# Activate 1

apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-pv-cert
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs/shareddir/website_cert
    server: 172.26.192.80 #<ip_address_of_kubernetes_master>
    # dit kan niet 127.0.0.1 zijn het moet het addres zijn van de cluster!!!